branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  # Analyze commits
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: docs
          release: false
        - type: style
          release: false
        - type: chore
          release: false
        - type: test
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        # BREAKING CHANGE
        - breaking: true
          release: major

  # 2. Create release notes
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "✨ Features"
            hidden: false
          - type: fix
            section: "🐛 Bug Fixes"
            hidden: false
          - type: perf
            section: "⚡ Performance"
            hidden: false
          - type: refactor
            section: "♻️ Refactoring"
            hidden: false
          - type: docs
            section: "📚 Documentation"
            hidden: true
          - type: chore
            section: "🔧 Maintenance"
            hidden: true

  # 3. update changelog file
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: |
        # 📋 Changelog

        All notable changes to FastClean will be documented in this file.

        This project adheres to [Semantic Versioning](https://semver.org/).

  # update version in pyproject.toml
  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i 's/^version = .*/version = "${nextRelease.version}"/' pyproject.toml

  # change commit
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - pyproject.toml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # 6. GitHub Release
  - - "@semantic-release/github"
    - assets: []
      successComment: |
        🎉 This ${issue.pull_request ? 'PR' : 'issue'} is included in version ${nextRelease.version}
      failComment: false
      labels: ["released"]
